### ISSUE TITLE
TrackerHit transmission

### ISSUE THREAD

**Issue by fucd** [cepc/CEPCSW#26]
Hi Mingrui @mirguest @zoujh ,

It seems that using ConstTrackerHit is our consensus. But object or pointer, which is best for transmission? I tend to pointer. My consider is:
1. Almost all tracking algorithm add tracker hit object into a hit helper class (for example, TrackerHitExtended in SiliconTrackingAlg), and then use the pointer of object saved in helper class will workable. 
2. If transmit object, although the size of object is small (~10 bytes?), for thousands hits, the cost is 10 thousands bytes level memory and CPU time in each copy. The copy times are different for different algorithm. If ~10 times, it will be 100kb level. Is it worth to save the cost through transmit pointer in event? 

Of course, the requirement is that each whole event is deal in one memory manager. I am not so clear on how multithreading work. So if it cannot work for multithreading, please let me know.

Chengdong

**Comment by fucd** [comment]
@zhaomr13

**Comment by zhaomr13** [comment]
For the thing that Chengdong concerning, if you look at the source code of plcio: http://cepcgit.ihep.ac.cn/cepc-prototype/plcio/-/blob/CEPC/source/datamodel/src/TrackerHit.cc (And I think the podio should be the same). Inside the TrackerHit/ConstTrackerHit type, there is a data member of TrackerHitObj, who contains the real data. When assigning a trackerHit to another trackerHit, it will only assign the reference of the trackerhit object(l.53 - l.40). So that we do not need to worry about the large time costing and we do not need to use TrackerHit*.

**Comment by zhaomr13** [comment]
I strongly support to use object.

**Comment by fucd** [comment]
Hi @zhaomr13 

Yes, I also discuss with Jiaheng and Tao, they worry about multithreading. The benefit is too small to venture. I agree too now.
Thanks very much for your reply.

Chengdong
