### ISSUE TITLE
WIP: Discuss the directory hierarchy

### ISSUE THREAD

**Issue by mirguest** [cepc/CEPCSW#43]
**Problem**: there are several extra code are copied into CEPCSW, which breaks the previous convention on the directory hierarchy.

### Top Level
* Top level (following the data processing flow)
  * Generator
  * Simulation (Detector Simulation)
  * Digitization
  * Calibration
  * Reconstruction
  * Analysis
  * Detector (Detector description)
  * Examples (all the job options here)

**Comment by fucd** [comment]
Hi @mirguest 

Maybe a top level directory Analysis is also needed.

Chengdong

**Comment by mirguest** [comment]
> Hi @mirguest
> 
> Maybe a top level directory Analysis is also needed.
> 
> Chengdong

@fucd Sure, I have updated this issue. Thanks.

**Comment by zhaomr13** [comment]
Hi @mirguest ,

Service/Tool is concept of Gaudi and Simulation/Reconstruction/.. is concept of software processing flow. They will have overlap. What's your idea to organize them?

I suggest to remove the service since they are some utilities. 
In addition, to make use of the "tool" of Gaudi. I suggest to remove the "algorithm" name of the processor and name it as the function. For example, Clupatra is the name of the processor the reconstruct TPC track. Currently it names ClupatraAlg. I suppose to name it TPCTrackingAlg instead. In the future, we can strip the interface part to TPCTrackingAlg and put the algorithm part to ClupatraTrackingTool.

Based on this idea. I suggest to put things like:

+ Generator 
+ Simulation
+ Digitization
+ Calibration
+ Tracking
    + TPCTrackingAlg
    + ClupatraTrackingTool
    + NewClupatraTrackingTool
    + AnotherClupatraTrackingTool
    + SiliconTrackingAlg
    + **TrkUtilities** (Here to put the services, tools, and external packages common for tracking, for example KalTest)
+ PFA
+ **Utilities**
+ ...

Mingrui.
